version: "3.3"
services:
  db:
     image: mysql:8.0
     command: --default-authentication-plugin=mysql_native_password
     environment:
       MYSQL_DATABASE: social
       MYSQL_USER: social
       MYSQL_PASSWORD: social
       MYSQL_RANDOM_ROOT_PASSWORD: 1
     ports:
       - "23306:3306"
     volumes:
       - ./var/mysql-data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE: social:social@(db:3306)/social
    restart: unless-stopped
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    ports:
      - "8001:80"
    environment:
      API_HOST: http://localhost:8000
    depends_on:
      - db
      - backend
